# Form implementation generated from reading ui file 'stimulator.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(617, 396)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 591, 341))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_play = QtWidgets.QPushButton(parent=self.widget)
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout.addWidget(self.btn_play)
        self.btn_play24 = QtWidgets.QPushButton(parent=self.widget)
        self.btn_play24.setObjectName("btn_play24")
        self.horizontalLayout.addWidget(self.btn_play24)
        self.btn_stop = QtWidgets.QPushButton(parent=self.widget)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_pause = QtWidgets.QPushButton(parent=self.widget)
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_lightbar = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_lightbar.sizePolicy().hasHeightForWidth())
        self.btn_lightbar.setSizePolicy(sizePolicy)
        self.btn_lightbar.setAutoRepeatDelay(300)
        self.btn_lightbar.setObjectName("btn_lightbar")
        self.verticalLayout_2.addWidget(self.btn_lightbar)
        self.btn_buzzer = QtWidgets.QPushButton(parent=self.widget)
        self.btn_buzzer.setObjectName("btn_buzzer")
        self.verticalLayout_2.addWidget(self.btn_buzzer)
        self.btn_headphone = QtWidgets.QPushButton(parent=self.widget)
        self.btn_headphone.setObjectName("btn_headphone")
        self.verticalLayout_2.addWidget(self.btn_headphone)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.stackedContainer = QtWidgets.QWidget(parent=self.widget)
        self.stackedContainer.setObjectName("stackedContainer")
        self.horizontalLayout_2.addWidget(self.stackedContainer)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 617, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EMDR Controller"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_play24.setText(_translate("MainWindow", "Play 24"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_pause.setText(_translate("MainWindow", "Pause"))
        self.btn_lightbar.setText(_translate("MainWindow", "Lightbar"))
        self.btn_buzzer.setText(_translate("MainWindow", "Buzzer"))
        self.btn_headphone.setText(_translate("MainWindow", "Headphone"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
